name: V1 Builds

on:
  schedule:
    # On 45-th minute, every 6 hours
    - cron:  '45 */6 * * *'

  push:
    branches:
    - 'v1-**'
    paths-ignore:
    - data/**
    - docs/**
    - '**/*.md'
#  pull_request:
#    branches:
#    - 'v1-**'
#    paths-ignore:
#    - data/**
#    - docs/**
#    - '**/*.md'

jobs:
  generate:
    name: Generate v1-bugfix-2.0.x
    runs-on: ubuntu-latest

    env:
      MIRROR_BRANCH: bugfix-2.0.x
      BUILD_BRANCH: v1-bugfix-2.0.x

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    # Based on .github/workflows/test-builds.yml
    - name: Select Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install PlatformIO
      run: |
        pip install -U https://github.com/platformio/platformio-core/archive/master.zip
        platformio update

    - name: Set git identity
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git config --global advice.detachedHead false

    - name: Generate
      run: |
        v1-scripts/fetch-branch "origin/$BUILD_BRANCH"
        git fetch --prune origin "$MIRROR_BRANCH" # We need full history of the mirror branch
        git branch $MIRROR_BRANCH origin/$MIRROR_BRANCH
        v1-scripts/generate-build-branch

    - name: Check
      run: |
        v1-scripts/diff-branches "$BUILD_BRANCH" "origin/$BUILD_BRANCH" && exit 0 # No changes
        v1-scripts/build-for-machine MPCNC/Rambo_T8_16T_LCD_DualEndstop

    - name: Push
      if: github.event_name != 'pull_request'
      run: |
        git push origin "$BUILD_BRANCH:refs/heads/$BUILD_BRANCH" --force

  build:

    name: ${{ matrix.machine }}
    runs-on: ubuntu-latest
    needs: generate

    strategy:
      fail-fast: false # Allow all machines to finish building
      matrix:
        machine:
        - MP3DP/MRambo_16T_aero
        - MP3DP/Ramps_16T_MK
        #- MPCNC/Archim1_T8_16T_LCD
        #- MPCNC/Archim1_T8_16T_LCD_DualEndstop
        #- MPCNC/Archim2_T8_16T_LCD_16step
        - MPCNC/MRambo_T8_16T_LCD
        - MPCNC/Rambo_T8_16T_LCD
        - MPCNC/Rambo_T8_16T_LCD_DualEndstop
        - MPCNC/Ramps_T8_16T_LCD_32step
        - MPCNC/Ramps_T8_16T_LCD_32step_DualEndstop
        - ZenXY/MiniRambo_16T
        - ZenXY/Ramps_16T_LCD_32

    steps:
    - name: Check out the code
      uses: actions/checkout@v2
      with:
        ref: v1-bugfix-2.0.x

    # Based on .github/workflows/test-builds.yml
    - name: Select Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install PlatformIO
      run: |
        pip install -U https://github.com/platformio/platformio-core/archive/master.zip
        platformio update

    - name: Build ${{ matrix.machine.cfg }}
      run: |
        chmod +x buildroot/bin/*
        chmod +x buildroot/share/tests/*
        v1-scripts/build-for-machine ${{ matrix.machine }}
        v1-scripts/prepare-release ${{ matrix.machine }}

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ".zip/*.zip,.bin/*"
        #bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        name: unstable
        # FIXME: This needs to be dynamic and possibly use a different action
        # e.g. https://github.com/actions/create-release/pull/12
        tag: v1-bugfix-2.0.x-auto
        commit: ${{ github.ref }}
        allowUpdates: true
